# Generated by Django 6.0 on 2026-07-17 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_components', '0003_alter_bookedcar_customer_email_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bookedcar',
            constraint=models.UniqueConstraint(fields=('car',), name='unique_car_booking'),
        ),
    ]
