# Generated by Django 6.0 on 2026-07-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_components', '0017_profile_is_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedcar',
            name='status',
            field=models.CharField(default='BOOKED', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
