# Generated by Django 6.0 on 2026-08-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_components', '0019_bookedcar_end_point_bookedcar_start_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedcar',
            name='distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookedcar',
            name='end_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookedcar',
            name='end_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookedcar',
            name='start_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookedcar',
            name='start_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='price_per_km',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
