# Generated by Django 6.0 on 2026-07-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_components', '0002_bookedcar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedcar',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='bookedcar',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
