# Generated by Django 6.0 on 2026-07-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_components', '0004_bookedcar_unique_car_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedcar',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='bookedcar',
            name='status',
            field=models.CharField(choices=[('BOOKED', 'Booked'), ('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled')], default='BOOKED', max_length=20),
        ),
    ]
