# Generated by Django 6.0 on 2026-07-21 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_components', '0006_remove_bookedcar_otp_bookedcar_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedcar',
            name='booked_at',
        ),
        migrations.AddField(
            model_name='bookedcar',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookedcar',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_components.car'),
        ),
        migrations.AlterField(
            model_name='bookedcar',
            name='customer_name',
            field=models.CharField(default='Guest', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookedcar',
            name='status',
            field=models.CharField(default='BOOKED', max_length=20),
        ),
    ]
