# Generated by Django 6.0 on 2026-07-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_components', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='latitude',
            field=models.FloatField(default=28.6139),
        ),
        migrations.AddField(
            model_name='car',
            name='longitude',
            field=models.FloatField(default=77.209),
        ),
    ]
