# Generated by Django 6.0 on 2026-07-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_components', '0012_alter_profile_is_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_driver',
            field=models.BooleanField(default=False),
        ),
    ]
