# Generated by Django 6.0 on 2026-07-31 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_components', '0015_remove_bookedcar_owner_car_owner'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bookedcar',
            name='unique_car_booking',
        ),
    ]
