# Generated by Django 6.0 on 2026-08-06 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_components', '0018_alter_bookedcar_status_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedcar',
            name='end_point',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookedcar',
            name='start_point',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
