# Generated by Django 6.0 on 2026-08-13 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_components', '0020_bookedcar_distance_km_bookedcar_end_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedcar',
            name='trip_type',
            field=models.CharField(choices=[('DATE_RANGE', 'Multi-day Rental'), ('POINT_TO_POINT', 'One-way Trip')], default='DATE_RANGE', max_length=20),
        ),
    ]
