# Generated by Django 6.0 on 2026-08-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_components', '0021_bookedcar_trip_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedcar',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookedcar',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
