# Generated by Django 6.0 on 2026-08-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_components', '0022_alter_bookedcar_end_date_alter_bookedcar_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedcar',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
