# Generated by Django 6.0 on 2026-08-23 09:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_components', '0024_profile_driver_license_profile_driver_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='owner_insurance',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='owner_puc',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='owner_rc',
        ),
        migrations.AddField(
            model_name='car',
            name='insurance_document',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='car',
            name='puc_document',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='car',
            name='rc_document',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
